/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import main.Shop;



/**
 *
 * @author jachias
 */
public class ShopView extends javax.swing.JFrame implements ActionListener, KeyListener {

    public Shop tienda;
    public int option = 0;
    
    /**
     * Creates new form ShopView
     */
    public ShopView() {
        initComponents();
        Shop shop = new Shop();
        try {
            shop.loadInventory();
        } catch (IOException ex) {
            Logger.getLogger(ShopView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void openCashView() {
        Shop shop = new Shop();
        CashView cashView = new CashView(shop);
        cashView.setVisible(true);
    }
    
    public void openProductView() {
        Shop shop = new Shop();
        ProductView productView = new ProductView(shop, option);
        productView.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAddProd = new javax.swing.JButton();
        jBCount = new javax.swing.JButton();
        jBAddStock = new javax.swing.JButton();
        jBDeleteProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBImportInv1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBAddProd.setText("2. Añadir producto");
        jBAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddProdActionPerformed(evt);
            }
        });

        jBCount.setText("1. Contar caja");
        jBCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCountActionPerformed(evt);
            }
        });

        jBAddStock.setText("3. Añadir stock");
        jBAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddStockActionPerformed(evt);
            }
        });

        jBDeleteProd.setText("9. Eliminar producto");
        jBDeleteProd.setToolTipText("");
        jBDeleteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteProdActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione una opción:");

        jBImportInv1.setText("0. Importar inventario");
        jBImportInv1.setToolTipText("");
        jBImportInv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImportInv1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jBCount, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBDeleteProd, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBImportInv1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDeleteProd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBImportInv1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddProdActionPerformed
         option = 1;
        openProductView();
    }//GEN-LAST:event_jBAddProdActionPerformed

    private void jBCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCountActionPerformed
        openCashView();
    }//GEN-LAST:event_jBCountActionPerformed

    private void jBAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddStockActionPerformed
        // TODO add your handling code here:
        option = 2;
        openProductView();
    }//GEN-LAST:event_jBAddStockActionPerformed

    private void jBDeleteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteProdActionPerformed
        // TODO add your handling code here:
        option = 9;
        openProductView();
    }//GEN-LAST:event_jBDeleteProdActionPerformed

    private void jBImportInv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImportInv1ActionPerformed
        // TODO add your handling code here:
        option = 10;
        
        JOptionPane.showMessageDialog(null, "El inventario ha sido exportado", "Info", JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(null, "No se ha podido exportar el inventario", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jBImportInv1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddProd;
    private javax.swing.JButton jBAddStock;
    private javax.swing.JButton jBCount;
    private javax.swing.JButton jBDeleteProd;
    private javax.swing.JButton jBImportInv1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
